In [67]:
import pandas as pd

# Import the CSV files
# These paths may need refinment after repo restructuring
july_data = pd.read_csv('JC-202307-citibike-tripdata.csv')
august_data = pd.read_csv('JC-202308-citibike-tripdata.csv')
september_data = pd.read_csv('JC-202309-citibike-tripdata.csv')

In [68]:
# Visualize dataframe
july_data.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7A68381621C25F78,classic_bike,2023-07-17 17:16:34,2023-07-17 17:20:52,Astor Place,JC077,Communipaw & Berry Lane,JC084,40.719225,-74.071281,40.714358,-74.066611,member
1,0F814CA67B2FA120,classic_bike,2023-07-26 19:40:15,2023-07-26 19:44:37,Adams St & 2 St,HB407,9 St HBLR - Jackson St & 8 St,HB305,40.739727,-74.036866,40.747907,-74.038412,member
2,775A38967EBF5FB4,electric_bike,2023-07-01 12:12:22,2023-07-01 12:27:45,McGinley Square,JC055,Riverview Park,JC057,40.725340,-74.067622,40.744319,-74.043991,member
3,D93B742DCE1C1447,classic_bike,2023-07-20 19:10:18,2023-07-20 19:17:22,Baldwin at Montgomery,JC020,Brunswick St,JC023,40.723455,-74.064359,40.724176,-74.050656,member
4,AA7A6863B4B92169,electric_bike,2023-07-07 19:33:59,2023-07-07 19:58:17,Baldwin at Montgomery,JC020,Mama Johnson Field - 4 St & Jackson St,HB404,40.723659,-74.064194,40.743140,-74.040041,casual

In [69]:
# Visualize dataframe
august_data.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,E2E964A161F786AB,classic_bike,2023-08-07 19:37:47,2023-08-07 19:41:14,6 St & Grand St,HB302,Madison St & 10 St,HB503,40.744398,-74.034501,40.749943,-74.035865,member
1,0660F2E48E3BB87F,classic_bike,2023-08-01 13:16:22,2023-08-01 13:26:02,6 St & Grand St,HB302,6 St & Grand St,HB302,40.744398,-74.034501,40.744398,-74.034501,member
2,940FC7C675232897,classic_bike,2023-08-15 17:28:23,2023-08-15 17:50:35,Heights Elevator,JC059,Heights Elevator,JC059,40.748721,-74.040480,40.748716,-74.040443,member
3,E967660CC5CD585B,classic_bike,2023-08-01 12:44:24,2023-08-01 12:49:45,Hoboken Ave at Monmouth St,JC105,Hoboken Terminal - River St & Hudson Pl,HB102,40.735279,-74.046830,40.736068,-74.029127,member
4,D997CB0B855FE2D6,classic_bike,2023-08-08 12:31:16,2023-08-08 12:40:18,Hoboken Ave at Monmouth St,JC105,Hoboken Terminal - River St & Hudson Pl,HB102,40.735208,-74.046964,40.736068,-74.029127,member

In [70]:
# Visualize dataframe
september_data.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,4052081EAF41D252,classic_bike,2023-09-01 17:25:27,2023-09-01 17:31:13,Baldwin at Montgomery,JC020,Liberty Light Rail,JC052,40.723484,-74.064445,40.711242,-74.055701,member
1,330043C418DD78E3,classic_bike,2023-09-01 12:57:39,2023-09-01 13:08:50,Baldwin at Montgomery,JC020,Exchange Pl,JC116,40.723503,-74.064276,40.716366,-74.034344,casual
2,4D0F3462818482CF,classic_bike,2023-09-28 08:52:24,2023-09-28 09:15:37,Baldwin at Montgomery,JC020,Baldwin at Montgomery,JC020,40.723508,-74.064379,40.723659,-74.064194,member
3,BF4A3EBF9352E283,classic_bike,2023-09-02 15:25:33,2023-09-02 15:57:11,Baldwin at Montgomery,JC020,Baldwin at Montgomery,JC020,40.723659,-74.064194,40.723659,-74.064194,casual
4,957FA73CA6E0C552,classic_bike,2023-09-14 16:46:42,2023-09-14 17:01:18,Baldwin at Montgomery,JC020,Paulus Hook,JC002,40.723659,-74.064194,40.714145,-74.033552,casual

In [71]:
# Merge the DataFrames
combined_data = pd.concat([july_data, august_data, september_data], ignore_index=True)

In [72]:
# Visualize cleaned dataframe
combined_data.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7A68381621C25F78,classic_bike,2023-07-17 17:16:34,2023-07-17 17:20:52,Astor Place,JC077,Communipaw & Berry Lane,JC084,40.719225,-74.071281,40.714358,-74.066611,member
1,0F814CA67B2FA120,classic_bike,2023-07-26 19:40:15,2023-07-26 19:44:37,Adams St & 2 St,HB407,9 St HBLR - Jackson St & 8 St,HB305,40.739727,-74.036866,40.747907,-74.038412,member
2,775A38967EBF5FB4,electric_bike,2023-07-01 12:12:22,2023-07-01 12:27:45,McGinley Square,JC055,Riverview Park,JC057,40.725340,-74.067622,40.744319,-74.043991,member
3,D93B742DCE1C1447,classic_bike,2023-07-20 19:10:18,2023-07-20 19:17:22,Baldwin at Montgomery,JC020,Brunswick St,JC023,40.723455,-74.064359,40.724176,-74.050656,member
4,AA7A6863B4B92169,electric_bike,2023-07-07 19:33:59,2023-07-07 19:58:17,Baldwin at Montgomery,JC020,Mama Johnson Field - 4 St & Jackson St,HB404,40.723659,-74.064194,40.743140,-74.040041,casual

In [73]:
# Visualize cleaned dataframe
combined_data.tail()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
312863,A2112D905D1B5FB9,electric_bike,2023-09-05 18:31:42,2023-09-05 18:35:31,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member
312864,2C9D64FF1B8C44C8,classic_bike,2023-09-25 08:36:13,2023-09-25 08:39:13,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.744306,-74.034534,40.752961,-74.024353,member
312865,4F4E24251BBAB45E,classic_bike,2023-09-19 07:55:23,2023-09-19 07:59:00,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member
312866,BB6F0D74150403AC,classic_bike,2023-09-14 07:50:23,2023-09-14 07:52:59,11 St & Washington St,HB502,14 St Ferry - 14 St & Shipyard Ln,HB202,40.749985,-74.027150,40.752961,-74.024353,member
312867,755AE0D4205C0306,classic_bike,2023-09-22 06:52:07,2023-09-22 06:55:49,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member

In [74]:
combined_data

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7A68381621C25F78,classic_bike,2023-07-17 17:16:34,2023-07-17 17:20:52,Astor Place,JC077,Communipaw & Berry Lane,JC084,40.719225,-74.071281,40.714358,-74.066611,member
1,0F814CA67B2FA120,classic_bike,2023-07-26 19:40:15,2023-07-26 19:44:37,Adams St & 2 St,HB407,9 St HBLR - Jackson St & 8 St,HB305,40.739727,-74.036866,40.747907,-74.038412,member
2,775A38967EBF5FB4,electric_bike,2023-07-01 12:12:22,2023-07-01 12:27:45,McGinley Square,JC055,Riverview Park,JC057,40.725340,-74.067622,40.744319,-74.043991,member
3,D93B742DCE1C1447,classic_bike,2023-07-20 19:10:18,2023-07-20 19:17:22,Baldwin at Montgomery,JC020,Brunswick St,JC023,40.723455,-74.064359,40.724176,-74.050656,member
4,AA7A6863B4B92169,electric_bike,2023-07-07 19:33:59,2023-07-07 19:58:17,Baldwin at Montgomery,JC020,Mama Johnson Field - 4 St & Jackson St,HB404,40.723659,-74.064194,40.743140,-74.040041,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
312863,A2112D905D1B5FB9,electric_bike,2023-09-05 18:31:42,2023-09-05 18:35:31,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member
312864,2C9D64FF1B8C44C8,classic_bike,2023-09-25 08:36:13,2023-09-25 08:39:13,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.744306,-74.034534,40.752961,-74.024353,member
312865,4F4E24251BBAB45E,classic_bike,2023-09-19 07:55:23,2023-09-19 07:59:00,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member
312866,BB6F0D74150403AC,classic_bike,2023-09-14 07:50:23,2023-09-14 07:52:59,11 St & Washington St,HB502,14 St Ferry - 14 St & Shipyard Ln,HB202,40.749985,-74.027150,40.752961,-74.024353,member
312867,755AE0D4205C0306,classic_bike,2023-09-22 06:52:07,2023-09-22 06:55:49,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member

In [75]:
# Export the combined DataFrame to a new CSV file
combined_data.to_csv('combined_data.csv', index=False)